// packages/design-to-code/src/web-components/form/controls/checkbox/control.checkbox.ts
import { attr, FASTElement } from "@microsoft/fast-element";

export class CheckboxControl extends FASTElement {
    @attr({ attribute: "data-location" })
    dataLocation: string;

    @attr({ mode: "boolean" })
    disabled: boolean;

    @attr({ mode: "boolean" })
    value: boolean;

    @attr({ mode: "boolean" })
    default: boolean;

    @attr
    checkbox: HTMLInputElement;

    /**
     * Fast Element lifecycle hook
     */
    public connectedCallback(): void {
        super.connectedCallback();

        if (typeof this.value !== "boolean") {
            this.value = this.default;
        }
    }

    public handleChange = e => {
        this.value = this.checkbox.checked;

        this.$emit("change");
    };

    public updateValidity = () => {
        this.$emit("dtc:form:update-validity");
    };
}

// packages/design-to-code-react/src/form/controls/control.checkbox.tsx
import React from "react";
import { CheckboxControlProps } from "./control.checkbox.props";
import { classNames } from "@microsoft/fast-web-utilities";
import { isDefault } from "./utilities/form";
import cssVariables from "../../style/css-variables.css";
import style from "./control.checkbox.style.css";

// tree-shaking
cssVariables;
style;

/**
 * Form control definition
 */
function CheckboxControl(props: CheckboxControlProps) {
    const value: boolean =
        typeof props.value === "boolean"
            ? props.value
            : typeof props.default === "boolean"
            ? props.default
            : false;

    function handleChange(): (e: React.ChangeEvent<HTMLInputElement>) => void {
        return (e: React.ChangeEvent<HTMLInputElement>): void => {
            props.onChange({ value: e.target.checked });
        };
    }

    return (
        <div
            className={classNames(
                "dtc-checkbox-control",
                ["dtc-checkbox-control__disabled", props.disabled],
                ["dtc-checkbox-control__default", isDefault(props.value, props.default)]
            )}
        >
            <input
                className={"dtc-checkbox-control_input"}
                id={props.dataLocation}
                type={"checkbox"}
                value={value.toString()}
                onChange={handleChange()}
                checked={value}
                disabled={props.disabled}
                ref={props.elementRef as React.Ref<HTMLInputElement>}
                onFocus={props.reportValidity}
                onBlur={props.updateValidity}
            />
            <span className={"dtc-checkbox-control_checkmark"} />
        </div>
    );
}

export { CheckboxControl };
export default CheckboxControl;
