// packages/design-to-code/src/web-components/form/controls/textarea/control.textarea.ts
import { attr, FASTElement } from "@microsoft/fast-element";

export class TextareaControl extends FASTElement {
    @attr
    value: string;

    @attr
    default: string;

    @attr({ attribute: "data-location" })
    dataLocation: string;

    @attr({ mode: "boolean" })
    disabled: boolean;

    @attr({ mode: "boolean" })
    required: boolean;

    @attr
    rows: string;

    @attr
    textarea: HTMLTextAreaElement;

    private focused: boolean = false;

    public reportValidity = () => {
        this.$emit("dtc:form:report-validity");
    };

    public updateValidity = () => {
        this.$emit("dtc:form:update-validity");
    };

    public getRows(): number {
        return typeof this.rows === "number" ? this.rows : 3;
    }

    public handleFocus(): void {
        this.reportValidity();

        this.focused = true;
    }

    public handleBlur(): void {
        this.updateValidity();

        this.focused = false;
    }

    public handleChange(): void {
        this.value = this.textarea.value;

        this.$emit("change");
    }

    public getValue(): string {
        // Return undefined to allow typing anywhere other than the end of the string
        // when the typing is occuring in the textarea
        if (this.focused) {
            return;
        }

        return typeof this.value === "string"
            ? this.value
            : typeof this.default === "string"
            ? this.default
            : "";
    }
}

// packages/design-to-code-react/src/form/controls/type/control.textarea.tsx
import React, { useState } from "react";
import { TextareaControlProps } from "./control.textarea.props";
import { classNames } from "@microsoft/fast-web-utilities";
import { isDefault } from "../utilities/form";
import cssVariables from "design-to-code/dist/stylesheets/web-components/style/global.css-variables.css";
import style from "./control.textarea.style.css";

// tree-shaking
cssVariables;
style;

/**
 * Form control definition
 */
function TextareaControl(props: TextareaControlProps) {
    const [focused, setFocus] = useState(false);

    function getRows(): number {
        return typeof props.rows === "number" ? props.rows : 3;
    }

    function getValue(): string {
        // Return undefined to allow typing anywhere other than the end of the string
        // when the typing is occuring in the textarea
        if (focused) {
            return;
        }

        return typeof props.value === "string"
            ? props.value
            : typeof props.default === "string"
            ? props.default
            : "";
    }

    function handleFocus(e: React.FocusEvent<HTMLTextAreaElement>): void {
        props.reportValidity();

        setFocus(true);
    }

    function handleBlur(e: React.FocusEvent<HTMLTextAreaElement>): void {
        props.updateValidity();

        setFocus(false);
    }

    function handleChange(): (e: React.ChangeEvent<HTMLTextAreaElement>) => void {
        return (e: React.ChangeEvent<HTMLTextAreaElement>): void => {
            props.onChange({ value: e.target.value });
        };
    }

    return (
        <textarea
            className={classNames(
                "dtc-textarea-control",
                ["dtc-textarea-control__disabled", props.disabled],
                ["dtc-textarea-control__default", isDefault(props.value, props.default)]
            )}
            id={props.dataLocation}
            name={props.dataLocation}
            rows={getRows()}
            value={getValue()}
            onChange={handleChange()}
            disabled={props.disabled}
            ref={props.elementRef as React.MutableRefObject<HTMLTextAreaElement>}
            onFocus={handleFocus}
            onBlur={handleBlur}
        />
    );
}

export { TextareaControl };
export default TextareaControl;
